import type { DestinationCategory, DestinationEntry, DestinationKind } from "./types";

type Seed = {
  id: string;
  label: string;
  kind: DestinationKind;
  aliases?: string[];
  categories: DestinationCategory[];
  popularity: number;
  searchWeight?: number;
  resolveCity?: string;
  parentCity?: string;
  subtitleKey?: string;
  osmId?: string;
  wikidataId?: string;
};

function entry(s: Seed): DestinationEntry {
  const slug = s.id;
  return {
    id: s.id,
    slug,
    kind: s.kind,
    label: s.label,
    aliases: s.aliases ?? [],
    categories: s.categories,
    popularity: s.popularity,
    searchWeight: s.searchWeight ?? s.popularity,
    resolveCity: s.resolveCity ?? s.label,
    parentCity: s.parentCity,
    subtitleKey: s.subtitleKey ?? s.categories[0],
    osmId: s.osmId,
    wikidataId: s.wikidataId,
  };
}

/** Level 1 — major booking / listing cities */
const CITIES: Seed[] = [
  {
    id: "marrakech",
    label: "Marrakech",
    kind: "city",
    aliases: ["Marrakesh", "مراكش", "Marrakech"],
    categories: ["city", "medina", "historic"],
    popularity: 100,
    searchWeight: 100,
    subtitleKey: "mostBooked",
    osmId: "relation/2799538",
    wikidataId: "Q101625",
  },
  {
    id: "casablanca",
    label: "Casablanca",
    kind: "city",
    aliases: ["Casa", "الدار البيضاء", "Casablanca", "Dar el Beida"],
    categories: ["city"],
    popularity: 98,
    searchWeight: 95,
    osmId: "relation/4072985",
    wikidataId: "Q7903",
  },
  {
    id: "agadir",
    label: "Agadir",
    kind: "city",
    aliases: ["أكادير", "Agadir"],
    categories: ["city", "beach"],
    popularity: 95,
    searchWeight: 90,
    subtitleKey: "beach",
    osmId: "relation/2529624",
    wikidataId: "Q170525",
  },
  {
    id: "taghazout",
    label: "Taghazout",
    kind: "city",
    aliases: ["Taghazoute", "تغازوت", "Taghazout"],
    categories: ["surf", "beach"],
    popularity: 94,
    searchWeight: 88,
    parentCity: "Agadir",
    subtitleKey: "surf",
    osmId: "relation/2758264",
    wikidataId: "Q21619246",
  },
  {
    id: "essaouira",
    label: "Essaouira",
    kind: "city",
    aliases: ["Mogador", "الصويرة", "Essaouira"],
    categories: ["city", "beach", "medina"],
    popularity: 92,
    searchWeight: 78,
    subtitleKey: "atlantic",
    osmId: "relation/2821038",
    wikidataId: "Q216939",
  },
  {
    id: "chefchaouen",
    label: "Chefchaouen",
    kind: "city",
    aliases: ["Chaouen", "Chefchaouan", "شفشاون", "Xauen", "Chefchaouen"],
    categories: ["medina", "mountain"],
    popularity: 90,
    searchWeight: 72,
    subtitleKey: "blueCity",
    osmId: "relation/6053065",
    wikidataId: "Q676778",
  },
  {
    id: "rabat",
    label: "Rabat",
    kind: "city",
    aliases: ["الرباط", "Rabat"],
    categories: ["city", "historic"],
    popularity: 88,
    searchWeight: 82,
    osmId: "relation/2799215",
    wikidataId: "Q3551",
  },
  {
    id: "tangier",
    label: "Tangier",
    kind: "city",
    aliases: ["Tanger", "Tangiers", "طنجة", "Tangier"],
    categories: ["city", "beach"],
    popularity: 87,
    searchWeight: 85,
    subtitleKey: "north",
    osmId: "relation/2758781",
    wikidataId: "Q126148",
  },
  {
    id: "merzouga",
    label: "Merzouga",
    kind: "city",
    aliases: ["مرزوقة", "Merzouga"],
    categories: ["desert"],
    popularity: 86,
    searchWeight: 75,
    subtitleKey: "sahara",
  },
  {
    id: "fes",
    label: "Fes",
    kind: "city",
    aliases: ["Fez", "Fès", "فاس", "Fes"],
    categories: ["city", "medina", "historic"],
    popularity: 85,
    searchWeight: 80,
    osmId: "relation/2799557",
    wikidataId: "Q80985",
  },
  {
    id: "ouarzazate",
    label: "Ouarzazate",
    kind: "city",
    aliases: ["ورزازات", "Ouarzazate", "Warzazat"],
    categories: ["city", "desert"],
    popularity: 82,
    searchWeight: 70,
  },
  {
    id: "tetouan",
    label: "Tetouan",
    kind: "city",
    aliases: ["Tétouan", "تطوان", "Tetuan"],
    categories: ["city", "medina"],
    popularity: 72,
    searchWeight: 60,
    osmId: "relation/2464649",
    wikidataId: "Q185157",
  },
  {
    id: "ifrane",
    label: "Ifrane",
    kind: "city",
    aliases: ["إفران", "Ifran", "Ifrane"],
    categories: ["mountain", "ski"],
    popularity: 78,
    searchWeight: 55,
    osmId: "relation/2819511",
    wikidataId: "Q1001887",
  },
  {
    id: "dakhla",
    label: "Dakhla",
    kind: "city",
    aliases: ["الداخلة", "Dakhla"],
    categories: ["beach", "surf"],
    popularity: 76,
    searchWeight: 65,
  },
  {
    id: "asilah",
    label: "Asilah",
    kind: "city",
    aliases: ["Assilah", "أصيلة", "Arzila"],
    categories: ["beach", "historic"],
    popularity: 68,
    searchWeight: 50,
  },
  {
    id: "al-hoceima",
    label: "Al Hoceima",
    kind: "city",
    aliases: ["Al-Hoceima", "الحسيمة", "Alhoceima"],
    categories: ["beach", "mountain"],
    popularity: 66,
    searchWeight: 48,
  },
  {
    id: "saidia",
    label: "Saidia",
    kind: "city",
    aliases: ["Saïdia", "السعيدية", "Saidia"],
    categories: ["beach"],
    popularity: 64,
    searchWeight: 45,
  },
  {
    id: "martil",
    label: "Martil",
    kind: "city",
    aliases: ["مارتيل", "Martil"],
    categories: ["beach"],
    popularity: 62,
    searchWeight: 44,
  },
  {
    id: "el-jadida",
    label: "El Jadida",
    kind: "city",
    aliases: ["الجديدة", "El Jadida", "Mazagan"],
    categories: ["city", "beach", "historic"],
    popularity: 70,
    searchWeight: 55,
  },
  {
    id: "safi",
    label: "Safi",
    kind: "city",
    aliases: ["آسفي", "Safi", "Asfi"],
    categories: ["city", "beach"],
    popularity: 58,
    searchWeight: 42,
  },
  {
    id: "nador",
    label: "Nador",
    kind: "city",
    aliases: ["الناظور", "Nador"],
    categories: ["city", "beach"],
    popularity: 56,
    searchWeight: 40,
  },
  {
    id: "oujda",
    label: "Oujda",
    kind: "city",
    aliases: ["وجدة", "Oujda"],
    categories: ["city"],
    popularity: 55,
    searchWeight: 40,
  },
  {
    id: "larache",
    label: "Larache",
    kind: "city",
    aliases: ["العرائش", "Larache", "El Araich"],
    categories: ["city", "beach"],
    popularity: 52,
    searchWeight: 38,
  },
  {
    id: "taza",
    label: "Taza",
    kind: "city",
    aliases: ["تازة", "Taza"],
    categories: ["city", "mountain"],
    popularity: 48,
    searchWeight: 35,
  },
  {
    id: "guelmim",
    label: "Guelmim",
    kind: "city",
    aliases: ["كلميم", "Guelmim", "Goulimine"],
    categories: ["city", "desert"],
    popularity: 50,
    searchWeight: 36,
  },
  {
    id: "laayoune",
    label: "Laayoune",
    kind: "city",
    aliases: ["El Aaiún", "العيون", "Laâyoune", "Laayoune"],
    categories: ["city"],
    popularity: 54,
    searchWeight: 40,
  },
  {
    id: "zagora",
    label: "Zagora",
    kind: "city",
    aliases: ["زاكورة", "Zagora"],
    categories: ["desert"],
    popularity: 60,
    searchWeight: 45,
  },
  {
    id: "midelt",
    label: "Midelt",
    kind: "city",
    aliases: ["ميدلت", "Midelt"],
    categories: ["mountain"],
    popularity: 46,
    searchWeight: 32,
  },
  {
    id: "azrou",
    label: "Azrou",
    kind: "city",
    aliases: ["أزرو", "Azrou"],
    categories: ["mountain"],
    popularity: 50,
    searchWeight: 38,
  },
  {
    id: "tinghir",
    label: "Tinghir",
    kind: "city",
    aliases: ["Tinerhir", "تنغير", "Tinghir"],
    categories: ["mountain", "nature"],
    popularity: 58,
    searchWeight: 42,
  },
  {
    id: "errachidia",
    label: "Errachidia",
    kind: "city",
    aliases: ["الرشيدية", "Errachidia", "Rachidia"],
    categories: ["city", "desert"],
    popularity: 55,
    searchWeight: 40,
  },
  {
    id: "meknes",
    label: "Meknes",
    kind: "city",
    aliases: ["مكناس", "Meknès", "Meknes"],
    categories: ["city", "historic", "medina"],
    popularity: 74,
    searchWeight: 65,
  },
  {
    id: "kenitra",
    label: "Kenitra",
    kind: "city",
    aliases: ["القنيطرة", "Kénitra", "Kenitra"],
    categories: ["city"],
    popularity: 52,
    searchWeight: 38,
  },
  {
    id: "sale",
    label: "Sale",
    kind: "city",
    aliases: ["Salé", "سلا", "Sale"],
    categories: ["city"],
    popularity: 58,
    searchWeight: 42,
  },
  {
    id: "mohammedia",
    label: "Mohammedia",
    kind: "city",
    aliases: ["المحمدية", "Mohammedia"],
    categories: ["city", "beach"],
    popularity: 54,
    searchWeight: 40,
  },
  {
    id: "beni-mellal",
    label: "Beni Mellal",
    kind: "city",
    aliases: ["بني ملال", "Beni Mellal"],
    categories: ["city", "mountain"],
    popularity: 50,
    searchWeight: 36,
  },
  {
    id: "taroudant",
    label: "Taroudant",
    kind: "city",
    aliases: ["تارودانت", "Taroudant"],
    categories: ["city", "historic"],
    popularity: 56,
    searchWeight: 40,
  },
  {
    id: "tiznit",
    label: "Tiznit",
    kind: "city",
    aliases: ["تزنيت", "Tiznit"],
    categories: ["city"],
    popularity: 48,
    searchWeight: 34,
  },
  {
    id: "tan-tan",
    label: "Tan-Tan",
    kind: "city",
    aliases: ["طانطان", "Tan Tan", "Tan-Tan"],
    categories: ["city", "desert"],
    popularity: 42,
    searchWeight: 30,
  },
  {
    id: "berkane",
    label: "Berkane",
    kind: "city",
    aliases: ["بركان", "Berkane"],
    categories: ["city"],
    popularity: 44,
    searchWeight: 32,
  },
  {
    id: "settat",
    label: "Settat",
    kind: "city",
    aliases: ["سطات", "Settat"],
    categories: ["city"],
    popularity: 40,
    searchWeight: 28,
  },
  {
    id: "khouribga",
    label: "Khouribga",
    kind: "city",
    aliases: ["خريبكة", "Khouribga"],
    categories: ["city"],
    popularity: 38,
    searchWeight: 26,
  },
  {
    id: "khemisset",
    label: "Khemisset",
    kind: "city",
    aliases: ["الخميسات", "Khémisset", "Khemisset"],
    categories: ["city"],
    popularity: 36,
    searchWeight: 24,
  },
];

/** Level 2 — tourist destinations (searchable; not listing cities) */
const TOURIST: Seed[] = [
  {
    id: "tamraght",
    label: "Tamraght",
    kind: "tourist_destination",
    aliases: ["تمراغت", "Tamraght"],
    categories: ["surf", "beach"],
    popularity: 80,
    resolveCity: "Agadir",
    parentCity: "Agadir",
    subtitleKey: "surf",
  },
  {
    id: "aourir",
    label: "Aourir",
    kind: "tourist_destination",
    aliases: ["أورير", "Aourir"],
    categories: ["surf", "beach"],
    popularity: 72,
    resolveCity: "Agadir",
    parentCity: "Agadir",
    subtitleKey: "surf",
  },
  {
    id: "imsouane",
    label: "Imsouane",
    kind: "tourist_destination",
    aliases: ["إمسوان", "Imsouane"],
    categories: ["surf", "beach"],
    popularity: 84,
    resolveCity: "Agadir",
    parentCity: "Agadir",
    subtitleKey: "surf",
  },
  {
    id: "mirleft",
    label: "Mirleft",
    kind: "tourist_destination",
    aliases: ["ميرلفت", "Mirleft"],
    categories: ["beach", "surf"],
    popularity: 70,
    resolveCity: "Tiznit",
    parentCity: "Tiznit",
    subtitleKey: "beach",
  },
  {
    id: "sidi-kaouki",
    label: "Sidi Kaouki",
    kind: "tourist_destination",
    aliases: ["سيدي كاوكي", "Sidi Kaouki", "Sidi Kaoukki"],
    categories: ["surf", "beach"],
    popularity: 68,
    resolveCity: "Essaouira",
    parentCity: "Essaouira",
    subtitleKey: "surf",
  },
  {
    id: "legzira",
    label: "Legzira",
    kind: "tourist_destination",
    aliases: ["Legzira Beach", "لغزيرة", "Plage Legzira"],
    categories: ["beach", "nature"],
    popularity: 66,
    resolveCity: "Tiznit",
    parentCity: "Tiznit",
    subtitleKey: "beach",
  },
  {
    id: "sidi-ifni",
    label: "Sidi Ifni",
    kind: "tourist_destination",
    aliases: ["سيدي إفني", "Sidi Ifni"],
    categories: ["beach"],
    popularity: 62,
    resolveCity: "Tiznit",
    parentCity: "Tiznit",
    subtitleKey: "beach",
  },
  {
    id: "paradise-valley",
    label: "Paradise Valley",
    kind: "tourist_destination",
    aliases: ["Vallée du Paradis", "وادي الجنة", "Paradise Valley"],
    categories: ["nature"],
    popularity: 74,
    resolveCity: "Agadir",
    parentCity: "Agadir",
    subtitleKey: "nature",
    osmId: "way/1135126726",
  },
  {
    id: "ourika",
    label: "Ourika",
    kind: "tourist_destination",
    aliases: ["Ourika Valley", "أوريكة", "Vallée de l'Ourika"],
    categories: ["nature", "mountain"],
    popularity: 76,
    resolveCity: "Marrakech",
    parentCity: "Marrakech",
    subtitleKey: "valley",
    osmId: "relation/3535324",
    wikidataId: "Q7111281",
  },
  {
    id: "agafay",
    label: "Agafay",
    kind: "tourist_destination",
    aliases: ["Agafay Desert", "أكفاي", "Désert d'Agafay"],
    categories: ["desert"],
    popularity: 78,
    resolveCity: "Marrakech",
    parentCity: "Marrakech",
    subtitleKey: "desert",
    osmId: "relation/2824275",
    wikidataId: "Q27538218",
  },
  {
    id: "ouzoud",
    label: "Ouzoud",
    kind: "tourist_destination",
    aliases: ["Ouzoud Falls", "Cascades d'Ouzoud", "شلالات أوزود"],
    categories: ["nature"],
    popularity: 72,
    resolveCity: "Beni Mellal",
    parentCity: "Beni Mellal",
    subtitleKey: "nature",
  },
  {
    id: "ait-benhaddou",
    label: "Ait Benhaddou",
    kind: "tourist_destination",
    aliases: ["Aït Benhaddou", "آيت بن حدو", "Ait Ben Haddou"],
    categories: ["historic", "medina"],
    popularity: 80,
    resolveCity: "Ouarzazate",
    parentCity: "Ouarzazate",
    subtitleKey: "historic",
  },
  {
    id: "skoura",
    label: "Skoura",
    kind: "tourist_destination",
    aliases: ["سكورة", "Skoura"],
    categories: ["desert", "nature"],
    popularity: 58,
    resolveCity: "Ouarzazate",
    parentCity: "Ouarzazate",
    subtitleKey: "desert",
  },
  {
    id: "tamegroute",
    label: "Tamegroute",
    kind: "tourist_destination",
    aliases: ["Tamgrout", "تامكروت", "Tamegroute"],
    categories: ["desert", "historic"],
    popularity: 52,
    resolveCity: "Zagora",
    parentCity: "Zagora",
    subtitleKey: "desert",
  },
  {
    id: "mhamid",
    label: "M'Hamid",
    kind: "tourist_destination",
    aliases: ["Mhamid", "محاميد الغزلان", "M'Hamid El Ghizlane"],
    categories: ["desert"],
    popularity: 54,
    resolveCity: "Zagora",
    parentCity: "Zagora",
    subtitleKey: "sahara",
  },
  {
    id: "moulay-bousselham",
    label: "Moulay Bousselham",
    kind: "tourist_destination",
    aliases: ["مولاي بوسلهام", "Moulay Bousselham"],
    categories: ["beach", "nature"],
    popularity: 56,
    resolveCity: "Kenitra",
    parentCity: "Kenitra",
    subtitleKey: "beach",
  },
  {
    id: "cabo-negro",
    label: "Cabo Negro",
    kind: "tourist_destination",
    aliases: ["Cap Negro", "كابو نيغرو", "Cabo Negro"],
    categories: ["beach"],
    popularity: 60,
    resolveCity: "Tetouan",
    parentCity: "Tetouan",
    subtitleKey: "beach",
  },
  {
    id: "oued-laou",
    label: "Oued Laou",
    kind: "tourist_destination",
    aliases: ["واد لاو", "Oued Laou"],
    categories: ["beach"],
    popularity: 55,
    resolveCity: "Tetouan",
    parentCity: "Tetouan",
    subtitleKey: "beach",
  },
  {
    id: "bin-el-ouidane",
    label: "Bin El Ouidane",
    kind: "tourist_destination",
    aliases: ["Bin el Ouidane", "بين الويدان", "Lac Bin El Ouidane"],
    categories: ["lake", "nature"],
    popularity: 58,
    resolveCity: "Beni Mellal",
    parentCity: "Beni Mellal",
    subtitleKey: "lake",
  },
  {
    id: "akchour",
    label: "Akchour",
    kind: "tourist_destination",
    aliases: ["Akchour Waterfalls", "أكشور", "Cascades d'Akchour"],
    categories: ["nature", "mountain"],
    popularity: 70,
    resolveCity: "Chefchaouen",
    parentCity: "Chefchaouen",
    subtitleKey: "nature",
  },
  {
    id: "fnideq",
    label: "Fnideq",
    kind: "tourist_destination",
    aliases: ["فنيدق", "Fnideq", "Castillejos"],
    categories: ["beach", "city"],
    popularity: 58,
    resolveCity: "Tetouan",
    parentCity: "Tetouan",
    subtitleKey: "beach",
  },
  {
    id: "medina-marrakech",
    label: "Medina",
    kind: "tourist_destination",
    aliases: ["Médina", "المدينة", "Old Medina", "Marrakech Medina"],
    categories: ["medina", "historic"],
    popularity: 65,
    resolveCity: "Marrakech",
    parentCity: "Marrakech",
    subtitleKey: "medina",
    osmId: "node/660578140",
    wikidataId: "Q966780",
  },
];

/** Level 3 — landmarks (searchable; not listing cities; excluded from Popular) */
const LANDMARKS: Seed[] = [
  {
    id: "hassan-ii-mosque",
    label: "Hassan II Mosque",
    kind: "landmark",
    aliases: ["Mosquée Hassan II", "مسجد الحسن الثاني", "Hassan 2 Mosque"],
    categories: ["historic"],
    popularity: 85,
    resolveCity: "Casablanca",
    parentCity: "Casablanca",
    subtitleKey: "historic",
  },
  {
    id: "jemaa-el-fnaa",
    label: "Jemaa el-Fnaa",
    kind: "landmark",
    aliases: ["Jemma el-Fna", "ساحة جامع الفنا", "Place Jemaa el-Fnaa", "Djema el-Fna"],
    categories: ["historic", "medina"],
    popularity: 92,
    resolveCity: "Marrakech",
    parentCity: "Marrakech",
    subtitleKey: "historic",
  },
  {
    id: "majorelle-garden",
    label: "Majorelle Garden",
    kind: "landmark",
    aliases: ["Jardin Majorelle", "حديقة ماجوريل", "Majorelle"],
    categories: ["nature", "historic"],
    popularity: 82,
    resolveCity: "Marrakech",
    parentCity: "Marrakech",
    subtitleKey: "nature",
  },
  {
    id: "chefchaouen-medina",
    label: "Chefchaouen Medina",
    kind: "landmark",
    aliases: ["Médina de Chefchaouen", "مدينة شفشاون", "Blue Medina"],
    categories: ["medina", "historic"],
    popularity: 86,
    resolveCity: "Chefchaouen",
    parentCity: "Chefchaouen",
    subtitleKey: "medina",
  },
  {
    id: "todra-gorge",
    label: "Todra Gorge",
    kind: "landmark",
    aliases: ["Gorges du Todra", "مضايق تودغا", "Todgha Gorge"],
    categories: ["nature", "mountain"],
    popularity: 75,
    resolveCity: "Tinghir",
    parentCity: "Tinghir",
    subtitleKey: "nature",
  },
  {
    id: "dades-gorge",
    label: "Dades Gorge",
    kind: "landmark",
    aliases: ["Gorges du Dadès", "مضايق دادس", "Dadès Gorge"],
    categories: ["nature", "mountain"],
    popularity: 72,
    resolveCity: "Ouarzazate",
    parentCity: "Ouarzazate",
    subtitleKey: "nature",
  },
  {
    id: "cap-spartel",
    label: "Cap Spartel",
    kind: "landmark",
    aliases: ["Cape Spartel", "رأس سبارطيل", "Cap Spartel"],
    categories: ["nature", "beach"],
    popularity: 68,
    resolveCity: "Tangier",
    parentCity: "Tangier",
    subtitleKey: "nature",
  },
  {
    id: "hercules-caves",
    label: "Hercules Caves",
    kind: "landmark",
    aliases: ["Caves of Hercules", "مغارة هرقل", "Grottes d'Hercule"],
    categories: ["nature", "historic"],
    popularity: 70,
    resolveCity: "Tangier",
    parentCity: "Tangier",
    subtitleKey: "nature",
  },
];

export const DESTINATION_CATALOG: DestinationEntry[] = [
  ...CITIES,
  ...TOURIST,
  ...LANDMARKS,
].map(entry);
