import type { Config } from "tailwindcss";
import { LAYERS, LAYER_CLASS } from "./lib/ui/layers";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: Object.values(LAYER_CLASS),
  theme: {
    extend: {
      zIndex: {
        "layer-base": String(LAYERS.base),
        "layer-content": String(LAYERS.content),
        "layer-header": String(LAYERS.header),
        "layer-sticky": String(LAYERS.sticky),
        "layer-dropdown": String(LAYERS.dropdown),
        "layer-popover": String(LAYERS.popover),
        "layer-date-picker": String(LAYERS.datePicker),
        "layer-command-palette": String(LAYERS.commandPalette),
        "layer-drawer": String(LAYERS.drawer),
        "layer-modal": String(LAYERS.modal),
        "layer-toast": String(LAYERS.toast),
        "layer-tooltip": String(LAYERS.tooltip),
      },
      fontFamily: {
        display: ["var(--font-playfair)", "Georgia", "serif"],
        sans: ["var(--font-dm-sans)", "system-ui", "sans-serif"],
        arabic: ["var(--font-arabic)", "var(--font-dm-sans)", "system-ui", "sans-serif"],
      },
      colors: {
        nexa: {
          primary: "#C42A58",
          "primary-dark": "#A92C50",
          "primary-light": "#F4809A",
          "primary-soft": "#FDF0F3",
          accent: "#F9A86C",
          "accent-soft": "#FEF5EC",
          ink: "#1A1118",
          "ink-2": "#3D2B36",
          "ink-3": "#6B5460",
          "ink-4": "#79636E",
          line: "#EDE0E5",
          bg: "#FDFBFC",
          "bg-2": "#F8F2F5",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        sm: "8px",
        md: "14px",
        lg: "22px",
        xl: "32px",
        "messaging-bubble": "16px",
        "messaging-card": "20px",
        "messaging-panel": "24px",
        "messaging-composer": "24px",
        "messaging-dropdown": "16px",
        "messaging-search": "24px",
      },
      boxShadow: {
        "nexa-sm": "0 2px 8px rgba(232,80,122,0.08)",
        "nexa-md": "0 6px 24px rgba(232,80,122,0.12)",
        "nexa-lg": "0 16px 48px rgba(232,80,122,0.16)",
        "nexa-card": "0 4px 20px rgba(26,17,24,0.07)",
        "messaging-1": "0 2px 8px rgba(26,17,24,0.06)",
        "messaging-2": "0 8px 24px rgba(26,17,24,0.08)",
        "messaging-3": "0 16px 40px rgba(26,17,24,0.12)",
        "messaging-4": "0 24px 64px rgba(26,17,24,0.18)",
      },
      transitionDuration: {
        "messaging-press": "90ms",
        "messaging-hover": "120ms",
        "messaging-message": "180ms",
        "messaging-context": "200ms",
        "messaging-panel": "220ms",
        "messaging-modal": "250ms",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
