import type { ExploreCityModule } from "../types";

export const agadir: ExploreCityModule = {
  id: "agadir",
  slug: "agadir",
  city: "Agadir",
  countryCode: "MA",
  region: "souss_massa",
  aliases: ["أكادير", "Agadir"],
  tag: "atlantic_beach",
  timezone: "Africa/Casablanca",
  mapCenter: { lat: 30.4205162, lng: -9.5838532 },
  defaultZoom: 12,
  bounds: {
    southwest: { lat: 30.3507233, lng: -9.6765894 },
    northeast: { lat: 30.4933553, lng: -9.4840659 },
  },
  priority: 25,
  searchWeight: 90,
  popularity: 88,
  osmId: "relation/2529624",
  wikidataId: "Q170525",
  neighborhoods: [
    {
      id: "marina",
      slug: "marina",
      name: "Marina",
      aliases: ["Marina d'Agadir", "مارينا"],
      descriptor: "marina",
      lat: 30.4250461,
      lng: -9.6170696,
      featuredOrder: 1,
      searchWeight: 85,
      popularity: 84,
      osmId: "node/1057816240",
    },
    {
      id: "founty",
      slug: "founty",
      name: "Founty",
      aliases: ["Fonci", "فونتي"],
      descriptor: "beachfront",
      lat: 30.3945833,
      lng: -9.5931204,
      featuredOrder: 2,
      searchWeight: 80,
      popularity: 78,
      osmId: "node/3846571063",
    },
    {
      id: "talborjt",
      slug: "talborjt",
      name: "Talborjt",
      aliases: ["تالبرجت"],
      descriptor: "residential",
      lat: 30.4237254,
      lng: -9.5905693,
      featuredOrder: 3,
      searchWeight: 70,
      popularity: 68,
      osmId: "node/3855001058",
    },
    {
      id: "sonaba",
      slug: "sonaba",
      name: "Sonaba",
      aliases: ["سونابا"],
      descriptor: "beachfront",
      lat: 30.3996557,
      lng: -9.5878933,
      searchWeight: 65,
      popularity: 66,
      // Local beach quarter; OSM place tagging sparse — coords near Founty coast
    },
  ],
  nearbyDestinations: [
    {
      id: "taghazout",
      slug: "taghazout",
      name: "Taghazout",
      aliases: ["تغازوت", "Taghazoute"],
      type: "SURF",
      descriptor: "surf_spot",
      lat: 30.5846695,
      lng: -9.6784988,
      distanceKm: 20,
      searchWeight: 75,
      popularity: 80,
      osmId: "relation/2758264",
      wikidataId: "Q21619246",
      seasonTags: ["autumn", "winter", "spring"],
    },
    {
      id: "paradise-valley",
      slug: "paradise-valley",
      name: "Paradise Valley",
      aliases: ["Vallée du Paradis", "وادي الجنة"],
      type: "NATURE",
      descriptor: "nature",
      lat: 30.5876107,
      lng: -9.5310442,
      distanceKm: 25,
      searchWeight: 55,
      popularity: 70,
      osmId: "way/1135126726",
      seasonTags: ["spring", "autumn"],
    },
  ],
};
