import type { ExploreCityModule } from "../types";

export const fes: ExploreCityModule = {
  id: "fes",
  slug: "fes",
  city: "Fes",
  countryCode: "MA",
  region: "fes_meknes",
  aliases: ["Fez", "Fès", "فاس", "Fes"],
  tag: "spiritual_cultural",
  timezone: "Africa/Casablanca",
  mapCenter: { lat: 34.0346534, lng: -5.0161926 },
  defaultZoom: 12,
  bounds: {
    southwest: { lat: 33.9764285, lng: -5.0781791 },
    northeast: { lat: 34.0755055, lng: -4.9377101 },
  },
  priority: 40,
  searchWeight: 80,
  popularity: 82,
  osmId: "relation/2799557",
  wikidataId: "Q80985",
  neighborhoods: [
    {
      id: "fes-el-bali",
      slug: "fes-el-bali",
      name: "Fes el-Bali",
      aliases: ["Fès el-Bali", "Fès-Médina", "فاس البالي", "Medina"],
      descriptor: "historic_medina",
      lat: 34.0631192,
      lng: -4.9737999,
      featuredOrder: 1,
      searchWeight: 95,
      popularity: 94,
      osmId: "node/2184888154",
    },
    {
      id: "ville-nouvelle",
      slug: "ville-nouvelle",
      name: "Ville Nouvelle",
      aliases: ["Dar Dbibagh", "المدينة الجديدة", "Nouvelle Ville"],
      descriptor: "shopping_cafes",
      lat: 34.0295238,
      lng: -4.9948257,
      featuredOrder: 2,
      searchWeight: 75,
      popularity: 72,
      osmId: "node/4978244986",
    },
    {
      id: "mellah",
      slug: "mellah",
      name: "Mellah",
      aliases: ["الملاح", "Jewish Quarter"],
      descriptor: "historic_medina",
      lat: 34.0585,
      lng: -4.9785,
      searchWeight: 60,
      popularity: 65,
      // Historic Jewish quarter adjacent to Fès el-Bali (OSM “Mellah” often resolves to Meknes)
    },
  ],
  nearbyDestinations: [],
};
