import type { ExploreCityModule } from "../types";

export const ifrane: ExploreCityModule = {
  id: "ifrane",
  slug: "ifrane",
  city: "Ifrane",
  countryCode: "MA",
  region: "fes_meknes",
  aliases: ["إفران", "Ifran"],
  tag: "alpine_town",
  timezone: "Africa/Casablanca",
  mapCenter: { lat: 33.527605, lng: -5.107408 },
  defaultZoom: 13,
  bounds: {
    southwest: { lat: 33.4871881, lng: -5.1607378 },
    northeast: { lat: 33.5588494, lng: -5.0860222 },
  },
  priority: 60,
  searchWeight: 55,
  popularity: 70,
  osmId: "relation/2819511",
  wikidataId: "Q1001887",
  seasonTags: ["winter", "summer"],
  bestMonths: [6, 7, 8, 12, 1, 2],
  neighborhoods: [
    {
      id: "centre-ville",
      slug: "centre-ville",
      name: "Centre-ville",
      aliases: ["Downtown", "وسط المدينة", "Ifrane Center"],
      descriptor: "mountain_escape",
      lat: 33.527605,
      lng: -5.107408,
      featuredOrder: 1,
      searchWeight: 80,
      popularity: 75,
      osmId: "relation/2819511",
    },
  ],
  nearbyDestinations: [
    {
      id: "michlifen",
      slug: "michlifen",
      name: "Michlifen",
      aliases: ["Michlifen ski resort", "ميشليفن"],
      type: "MOUNTAIN",
      descriptor: "mountain_escape",
      lat: 33.4114157,
      lng: -5.0784055,
      distanceKm: 14,
      searchWeight: 50,
      popularity: 65,
      osmId: "way/752031203",
      seasonTags: ["winter"],
      bestMonths: [12, 1, 2, 3],
    },
  ],
};
