import type { ExploreCityModule } from "../types";

export const rabat: ExploreCityModule = {
  id: "rabat",
  slug: "rabat",
  city: "Rabat",
  countryCode: "MA",
  region: "rabat_sale_kenitra",
  aliases: ["الرباط", "Rabat"],
  tag: "capital_city",
  timezone: "Africa/Casablanca",
  mapCenter: { lat: 34.0218454, lng: -6.8408929 },
  defaultZoom: 12,
  bounds: {
    southwest: { lat: 33.8964011, lng: -6.9305776 },
    northeast: { lat: 34.0378472, lng: -6.7614635 },
  },
  priority: 35,
  searchWeight: 82,
  popularity: 80,
  osmId: "relation/2799215",
  wikidataId: "Q3551",
  neighborhoods: [
    {
      id: "agdal",
      slug: "agdal",
      name: "Agdal",
      aliases: ["أكدال"],
      descriptor: "university_area",
      lat: 33.9983119,
      lng: -6.8542908,
      featuredOrder: 1,
      searchWeight: 85,
      popularity: 84,
      osmId: "node/2184710850",
    },
    {
      id: "souissi",
      slug: "souissi",
      name: "Souissi",
      aliases: ["السويسي", "Souissi"],
      descriptor: "luxury_living",
      lat: 33.9688418,
      lng: -6.8348164,
      featuredOrder: 2,
      searchWeight: 80,
      popularity: 82,
      osmId: "node/2184710847",
    },
    {
      id: "hassan",
      slug: "hassan",
      name: "Hassan",
      aliases: ["حسان", "Arrondissement Hassan"],
      descriptor: "historic",
      lat: 34.0202422,
      lng: -6.8235174,
      featuredOrder: 3,
      searchWeight: 78,
      popularity: 76,
      osmId: "relation/4743369",
    },
    {
      id: "medina",
      slug: "medina",
      name: "Medina",
      aliases: ["Médina", "المدينة العتيقة", "Old Medina"],
      descriptor: "historic_medina",
      lat: 34.0255,
      lng: -6.8345,
      searchWeight: 75,
      popularity: 78,
      // Historic medina core within Hassan / Océan; OSM place node sparse
    },
  ],
  nearbyDestinations: [],
};
