import type { ExploreCityModule } from "../types";

export const tangier: ExploreCityModule = {
  id: "tangier",
  slug: "tangier",
  city: "Tangier",
  countryCode: "MA",
  region: "tanger_tetouan_al_hoceima",
  aliases: ["Tanger", "طنجة", "Tangiers"],
  tag: "europe_africa_gateway",
  timezone: "Africa/Casablanca",
  mapCenter: { lat: 35.7696302, lng: -5.8033522 },
  defaultZoom: 12,
  bounds: {
    southwest: { lat: 35.6995621, lng: -5.9484121 },
    northeast: { lat: 35.8259979, lng: -5.7135397 },
  },
  priority: 30,
  searchWeight: 85,
  popularity: 84,
  osmId: "relation/2758781",
  wikidataId: "Q126148",
  neighborhoods: [
    {
      id: "kasbah",
      slug: "kasbah",
      name: "Kasbah",
      aliases: ["قصبة", "Kasba", "Tangier Kasbah"],
      descriptor: "historic_medina",
      lat: 35.7887531,
      lng: -5.8134345,
      featuredOrder: 1,
      searchWeight: 88,
      popularity: 86,
      osmId: "node/2377506756",
    },
    {
      id: "malabata",
      slug: "malabata",
      name: "Malabata",
      aliases: ["Plage Malabata", "مالاباطا"],
      descriptor: "beachfront",
      lat: 35.7785399,
      lng: -5.7768691,
      featuredOrder: 2,
      searchWeight: 75,
      popularity: 72,
      osmId: "way/487158391",
    },
    {
      id: "marshan",
      slug: "marshan",
      name: "Marshan",
      aliases: ["مرشان"],
      descriptor: "residential",
      lat: 35.7900018,
      lng: -5.8207537,
      featuredOrder: 3,
      searchWeight: 70,
      popularity: 68,
      // Center derived from OSM POIs clustered in Marshan (place node sparse in OSM)
    },
    {
      id: "iberia",
      slug: "iberia",
      name: "Iberia",
      aliases: ["إيبريا"],
      descriptor: "shopping_cafes",
      lat: 35.7825706,
      lng: -5.8208983,
      searchWeight: 65,
      popularity: 64,
      osmId: "node/4993129394",
    },
  ],
  nearbyDestinations: [],
};
