/**
 * Moroccan cities for listing filters, host onboarding, and profile/registration.
 * Alphabetically sorted for dropdown UX.
 */
export const MOROCCO_CITIES: readonly string[] = [
  "Agadir",
  "Asilah",
  "Beni Mellal",
  "Berkane",
  "Casablanca",
  "Chefchaouen",
  "Dakhla",
  "El Jadida",
  "Errachidia",
  "Essaouira",
  "Fes",
  "Guelmim",
  "Ifrane",
  "Kenitra",
  "Khemisset",
  "Khouribga",
  "Laayoune",
  "Larache",
  "Marrakech",
  "Meknes",
  "Mohammedia",
  "Nador",
  "Ouarzazate",
  "Oujda",
  "Rabat",
  "Safi",
  "Sale",
  "Settat",
  "Tangier",
  "Tan-Tan",
  "Taroudant",
  "Taza",
  "Tetouan",
  "Tiznit",
].sort((a, b) => a.localeCompare(b, "en"));
