import type { GuideDefinition, GuideId } from "@/lib/guidance-types";

export const GUIDE_CATALOG: GuideDefinition[] = [
  {
    id: "welcome",
    type: "welcome",
    priority: "normal",
    trigger: "home_after_700ms",
    asset: "/guidance/welcom.png",
    cooldownSec: 30,
    once: true,
    enabled: true,
    rollout: 100,
    analytics: true,
    progress: { step: 1, of: 3 },
    titleKey: "guidance.welcomeTitle",
    bodyKey: "guidance.welcomeBody",
    primaryKey: "guidance.continue",
    secondaryKey: "guidance.notNow",
  },
  {
    id: "search_fab",
    type: "spotlight",
    priority: "normal",
    trigger: "after_welcome",
    target: "search-fab",
    cooldownSec: 30,
    once: true,
    enabled: true,
    rollout: 100,
    analytics: true,
    titleKey: "guidance.searchTitle",
    bodyKey: "guidance.searchBody",
    primaryKey: "guidance.startSearching",
    secondaryKey: "guidance.notNow",
  },
  {
    id: "save_first",
    type: "celebration",
    priority: "high",
    trigger: "first_save",
    asset: "/guidance/save.png",
    cooldownSec: 0,
    once: true,
    enabled: true,
    rollout: 100,
    analytics: true,
    titleKey: "guidance.savedTitle",
    bodyKey: "guidance.savedBody",
    primaryKey: "guidance.viewSaved",
    secondaryKey: "guidance.continue",
  },
  {
    id: "saved_tab",
    type: "spotlight",
    priority: "high",
    trigger: "after_save_first",
    target: "nav-saved",
    cooldownSec: 0,
    once: true,
    enabled: true,
    rollout: 100,
    analytics: true,
    titleKey: "guidance.savedTabTitle",
    bodyKey: "guidance.savedTabBody",
    primaryKey: "guidance.continue",
    secondaryKey: "guidance.notNow",
  },
  {
    id: "booking_success",
    type: "celebration",
    priority: "critical",
    trigger: "booking_complete",
    asset: "/guidance/trip.png",
    cooldownSec: 0,
    once: true,
    enabled: true,
    rollout: 100,
    analytics: true,
    titleKey: "guidance.bookingTitle",
    bodyKey: "guidance.bookingBody",
    primaryKey: "guidance.viewTrip",
    secondaryKey: "guidance.continue",
  },
  {
    id: "trips_tab",
    type: "spotlight",
    priority: "high",
    trigger: "after_booking_success",
    target: "nav-trips",
    cooldownSec: 0,
    once: true,
    enabled: true,
    rollout: 100,
    analytics: true,
    titleKey: "guidance.tripsTabTitle",
    bodyKey: "guidance.tripsTabBody",
    primaryKey: "guidance.continue",
    secondaryKey: "guidance.notNow",
  },
  {
    id: "install_app",
    type: "bottom_tip",
    priority: "high",
    trigger: "after_welcome_android",
    asset: "/guidance/phonemockup.png",
    cooldownSec: 30,
    once: true,
    enabled: true,
    rollout: 100,
    analytics: true,
    titleKey: "guidance.installTitle",
    bodyKey: "guidance.installBody",
    primaryKey: "guidance.installApp",
    secondaryKey: "guidance.notNow",
  },
  {
    id: "install_success",
    type: "success",
    priority: "critical",
    trigger: "app_installed",
    cooldownSec: 0,
    once: true,
    enabled: true,
    rollout: 100,
    analytics: true,
    titleKey: "guidance.installSuccessTitle",
    bodyKey: "guidance.installSuccessBody",
    primaryKey: "guidance.continue",
  },
  {
    id: "review_celebration",
    type: "celebration",
    priority: "high",
    trigger: "review_submitted",
    cooldownSec: 0,
    once: true,
    enabled: true,
    rollout: 100,
    analytics: true,
    titleKey: "guidance.reviewTitle",
    bodyKey: "guidance.reviewBody",
    primaryKey: "guidance.continue",
    secondaryKey: "guidance.notNow",
  },
];

export const GUIDE_BY_ID: Record<GuideId, GuideDefinition> = GUIDE_CATALOG.reduce(
  (acc, g) => {
    acc[g.id] = g;
    return acc;
  },
  {} as Record<GuideId, GuideDefinition>,
);
